name: Deploy to Firebase Functions

   on:
     push:
       branches:
         - main  # or your default branch name

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Use Node.js
           uses: actions/setup-node@v2
           with:
             node-version: '14'  # or whatever version you're using
         - name: Install Dependencies
           run: npm ci
         - name: Deploy to Firebase
           uses: w9jds/firebase-action@master
           with:
             args: deploy --only functions
           env:
             FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
   
